kestra-io/plugin-gcp

src/main/java/org/kestra/task/gcp/bigquery/ExtractToGcs.java, src/test/java/org/kestra/task/gcp/bigquery/ExtractToGcsTest.java
Add a task to extract a BigQuery table to a file into a bucket.
=> feat(): ExtractToGcs Bigquery task

src/main/java/io/kestra/plugin/gcp/bigquery/BigQueryService.java, src/main/java/io/kestra/plugin/gcp/bigquery/Copy.java, src/main/java/io/kestra/plugin/gcp/bigquery/ExtractToGcs.java, src/main/java/io/kestra/plugin/gcp/bigquery/Query.java, src/test/java/io/kestra/plugin/gcp/bigquery/BigQueryServiceTest.java
Fixes [#237](https://github.com/kestra-io/plugin-gcp/issues/237)
=> feat: add Kestra labels to BigQuery

src/main/java/io/kestra/plugin/gcp/pubsub/Consume.java, src/main/java/io/kestra/plugin/gcp/pubsub/Publish.java, src/main/java/io/kestra/plugin/gcp/pubsub/Trigger.java, src/main/java/io/kestra/plugin/gcp/pubsub/model/Message.java, src/main/java/io/kestra/plugin/gcp/pubsub/model/SerdeType.java, src/test/java/io/kestra/plugin/gcp/pubsub/PublishThenConsumeTest.java, src/test/java/io/kestra/plugin/gcp/pubsub/TriggerTest.java
=> feat: allow JSON messages for PubSub tasks

src/main/java/io/kestra/plugin/gcp/pubsub/Consume.java
=> fix: missing credential provider on the PubSub Consume task

src/main/java/io/kestra/plugin/gcp/bigquery/BigQueryService.java
BigQuery labels was not properly set
---
By checking that BigQuery Labels are good directly in Google Cloud Logging
---
=> fix: BigQuery labels was not properly set

src/main/java/io/kestra/plugin/gcp/bigquery/Load.java, src/main/java/io/kestra/plugin/gcp/bigquery/Query.java, src/main/java/io/kestra/plugin/gcp/bigquery/StorageWrite.java, src/main/java/io/kestra/plugin/gcp/firestore/Query.java, src/main/java/io/kestra/plugin/gcp/gcs/Download.java, src/main/java/io/kestra/plugin/gcp/gcs/Downloads.java, src/main/java/io/kestra/plugin/gcp/gcs/Trigger.java, src/main/java/io/kestra/plugin/gcp/gcs/Upload.java, src/main/java/io/kestra/plugin/gcp/pubsub/Consume.java, src/main/java/io/kestra/plugin/gcp/pubsub/Publish.java, src/main/java/io/kestra/plugin/gcp/vertexai/MultimodalCompletion.java
=> chore: migrate to new kestra core storage api

src/main/java/io/kestra/plugin/gcp/auth/OauthAccessToken.java, src/test/java/io/kestra/plugin/gcp/auth/OauthAccessTokenTest.java, src/test/resources/application.yml
~Waiting for https://github.com/kestra-io/kestra/pull/3005~
=> feat: encrypt the OauthAccessToken by default

src/main/java/io/kestra/plugin/gcp/cli/GCloudCLI.java
Corrected the gcloud cli examples.
Minor corrections in docs.
=> fix(docs): corrected the examples of gcloud cli

src/main/java/io/kestra/plugin/gcp/bigquery/Copy.java, src/main/java/io/kestra/plugin/gcp/bigquery/CopyPartitions.java, src/main/java/io/kestra/plugin/gcp/bigquery/DeletePartitions.java, src/main/java/io/kestra/plugin/gcp/bigquery/ExtractToGcs.java, src/main/java/io/kestra/plugin/gcp/bigquery/Load.java, src/main/java/io/kestra/plugin/gcp/bigquery/LoadFromGcs.java, src/main/java/io/kestra/plugin/gcp/bigquery/Query.java, src/main/java/io/kestra/plugin/gcp/bigquery/StorageWrite.java, src/main/java/io/kestra/plugin/gcp/bigquery/TableMetadata.java
=> feat(docs): Add metrics to BigQuery tasks

src/main/java/io/kestra/plugin/gcp/runner/GcpBatchTaskRunner.java, src/main/java/io/kestra/plugin/gcp/runner/GcpCloudRunTaskRunner.java
part-of: kestra-io/kestra#3700
=> feat: propagate kills to the TaskRunner

src/main/java/io/kestra/plugin/gcp/runner/GcpBatchTaskRunner.java, src/main/java/io/kestra/plugin/gcp/runner/GcpCloudRunTaskRunner.java, src/test/java/io/kestra/plugin/gcp/runner/GcpBatchTaskRunnerTest.java, src/test/java/io/kestra/plugin/gcp/runner/GcpCloudRunTaskRunnerTest.java
related-to: kestra-io/kestra#3701
=> feat(runner): add new completionCheckInterval property

src/main/java/io/kestra/plugin/gcp/runner/Batch.java, src/main/java/io/kestra/plugin/gcp/runner/CloudRun.java, src/main/java/io/kestra/plugin/gcp/runner/LogTail.java
Logs can be available in the log stream after the job ends as everything is anynchronous so we don't have any other option than to wait a little for them to arrives. This wait time is configurable and set to a conservative value of 5s.
Note that calling cancel() on the stream will make the stream iterator to return false to hasNext() effectively ending the stream, no need for a boolean for that.
Fixes https://github.com/kestra-io/kestra/issues/3695
=> fix: wait for logs in task runners

src/main/java/io/kestra/plugin/gcp/gcs/Downloads.java, src/test/java/io/kestra/plugin/gcp/gcs/DownloadsTest.java
=> feat: Add 'outputFiles' property with a map of file name / URI

src/main/java/io/kestra/plugin/gcp/pubsub/RealtimeTrigger.java, src/main/java/io/kestra/plugin/gcp/pubsub/Trigger.java
Correct realtime trigger examples
Ensure there is a link/mention from Triggers to Realtime Triggers and vice versa
=> fix(docs): add pub/sub realtime trigger description

src/main/java/io/kestra/plugin/gcp/runner/Batch.java
=> feat: retry getJob to avoid DeadlineExceededException

src/main/java/io/kestra/plugin/gcp/runner/CloudRun.java
=> feat: resume a CloudRUn task job

src/main/java/io/kestra/plugin/gcp/runner/Batch.java, src/main/java/io/kestra/plugin/gcp/runner/CloudRun.java, src/main/java/io/kestra/plugin/gcp/runner/GcsUtils.java
=> feat: task runner should dowload all output files from the output dir

src/main/java/io/kestra/plugin/gcp/pubsub/model/Message.java
Fixes https://github.com/kestra-io/plugin-gcp/issues/450
=> fix: don't base64 encode pubsub message

build.gradle
Closes #457
Closes #456
Closes #455
=> chore: dependency updates

src/main/java/io/kestra/plugin/gcp/bigquery/Query.java, src/main/java/io/kestra/plugin/gcp/bigquery/QueryInterface.java, src/main/java/io/kestra/plugin/gcp/bigquery/Trigger.java, src/test/java/io/kestra/plugin/gcp/bigquery/QueryTest.java
=> feat: introduce fetchType for Query and Trigger

src/main/java/io/kestra/plugin/gcp/AbstractTask.java, src/test/java/io/kestra/plugin/gcp/gcs/AbstractBucketTest.java, src/test/java/io/kestra/plugin/gcp/gcs/InferedProjectIdBucketTest.java
When projectId is null, then infer it from the Google Credentials
#2558
=> feat: infer project ID

src/main/java/io/kestra/plugin/gcp/bigquery/ExtractToGcs.java, src/main/java/io/kestra/plugin/gcp/bigquery/Query.java
=> fix: wrong null comparison in ExtractToGcs

src/main/java/io/kestra/plugin/gcp/cli/package-info.java
- part-of: https://github.com/kestra-io/kestra/issues/10631
=> fix(): subgroups for better readability
